name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myimage -f cosmos-fast/Dockerfile .
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  
      
    - name: Install Azure CLI
      run: |
        python -m pip install --upgrade azure-cli  
        
    
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
          registry: kyroreg.azurecr.io
          username: kyroreg
          password: 8QlSiawD+pc88sEPD1+s8r+qeXt6h7jUf9fT6tcYty+ACRA9sjnN

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
          push: true
          tags:  kyroreg.azurecr.io/kyro-container-app:${{ github.sha }}
          file: ./cosmos-fast/Dockerfile
          context: ./
          
  deploy:
      runs-on: ubuntu-latest
      needs: build
      
      steps:
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kyroregistry.azurecr.io/kyro-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./
