name: Trigger auto deployment for kyro-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'cosmos-fast/**'
    - '.github/workflows/kyro-app-AutoDeployTrigger-243e13cf-2391-4b78-9af0-4cf0dd9d29d1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: kyroregistory.azurecr.io
          username: ${{ secrets.KYROAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.KYROAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kyroregistory.azurecr.io/kyro-app:${{ github.sha }}
          file: ./cosmos-fast/Dockerfile
          context: ./cosmos-fast/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KYROAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kyro-app -g kyro-RGP --server kyroregistory.azurecr.io --username  ${{ secrets.KYROAPP_REGISTRY_USERNAME }} --password ${{ secrets.KYROAPP_REGISTRY_PASSWORD }}
            az containerapp update -n kyro-app -g kyro-RGP --image kyroregistory.azurecr.io/kyro-app:${{ github.sha }}
