name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install fastapi
        python -m pip install fastapi uvicorn
        python -m pip install uvicorn
        python -m pip install python-dotenv
        python -m pip install aiohttp
        python -m pip install azure-cosmos

    - name: Build and test application
      run: |

    - name: Build Docker image
      run: |
        docker build -t my-image -f cosmos-fast/Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KYROAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kyro-app -g kyro-RGP --server kryoreg.azurecr.io --username  ${{ secrets.KYROAPP_REGISTRY_USERNAME }} --password ${{ secrets.KYROAPP_REGISTRY_PASSWORD }}
            az containerapp update -n kyro-app -g kyro-RGP --image kryoreg.azurecr.io/kyro-app:${{ github.sha }}
