name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install fastapi
        python -m pip install fastapi uvicorn
        python -m pip install uvicorn
        python -m pip install python-dotenv
        python -m pip install aiohttp
        python -m pip install azure-cosmos

    - name: Build and test application
      run: |

    - name: Build Docker image
      run: |
        docker build -t my-image -f cosmos-fast/Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
   


      - name: Login to ACR
        run: az acr login --name kryoreg

      - name: Push image to ACR
        run: docker push kryoreg.azurecr.io/myimage:${{ env.GITHUB_SHA }}
  
env:
  AZURE_SP_ID: ${{ secrets.AZURE_SP_ID }}
  AZURE_SP_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
  AZURE_SP_TENANT: ${{ secrets.AZURE_SP_TENANT }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
